main: al.Duszafir.AntiLavaGrieff
version: 1.1.3
name: AntiLavaGrieff
author: Duszafir
api-version: 1.13

commands:
  antilavagrief:
    description: Main Command, /al <enable/disable>
    aliases:
      - al