main: al.Duszafir.AntiLavaGrieff
version: 1.0.1
name: AntiLavaGrieff
author: Duszafir
api-version: 1.13

commands:
  antilavagrief:
    description: Comando principal del plugin skibidi
    aliases:
      - al

